/**
 * config/images.ts
 *
 * Central image registry — all site images are defined here.
 * To swap an image: log into https://cloudinary.com/console,
 * upload the new photo to the "caps-website" folder with the same
 * Public ID, then the site will automatically serve the new image.
 *
 * Auto-generated by: node scripts/upload-to-cloudinary.mjs
 * Last updated: 2026-06-04T09:45:18.123Z
 */

const CLOUD = "https://res.cloudinary.com/douvu5qu2/image/upload";
const OPT = "f_auto,q_auto,w_auto"; // auto format, quality & width

export const images = {
  /** hero-home.jpg */
  heroHome: `${CLOUD}/${OPT}/caps-website/hero-home`,

  /** home-mentoring-writing.png */
  homeMentoringWriting: `${CLOUD}/${OPT}/caps-website/home-mentoring-writing`,

  /** home-workshops.png */
  homeWorkshops: `${CLOUD}/${OPT}/caps-website/home-workshops`,

  /** logo-dark.png */
  logoDark: `${CLOUD}/${OPT}/caps-website/logo-dark`,

  /** logo.png */
  logo: `${CLOUD}/${OPT}/caps-website/logo`,

  /** peer-network-center-1.JPG */
  peerNetworkCenter1: `${CLOUD}/${OPT}/caps-website/peer-network-center-1`,

  /** peer-network-center-2.JPG */
  peerNetworkCenter2: `${CLOUD}/${OPT}/caps-website/peer-network-center-2`,

  /** peer-network-floating-1.JPG */
  peerNetworkFloating1: `${CLOUD}/${OPT}/caps-website/peer-network-floating-1`,

  /** peer-network-floating-2.JPG */
  peerNetworkFloating2: `${CLOUD}/${OPT}/caps-website/peer-network-floating-2`,

  /** peer-network-floating-3.JPG */
  peerNetworkFloating3: `${CLOUD}/${OPT}/caps-website/peer-network-floating-3`,

  /** peer-network-floating-4.JPG */
  peerNetworkFloating4: `${CLOUD}/${OPT}/caps-website/peer-network-floating-4`,

  /** wing-connect-wide.jpg */
  wingConnectWide: `${CLOUD}/${OPT}/caps-website/wing-connect-wide`,

  /** wing-group-peer-training.png */
  wingGroupPeerTraining: `${CLOUD}/${OPT}/caps-website/wing-group-peer-training`,

  /** wing-one-on-one-peer-training.png */
  wingOneOnOnePeerTraining: `${CLOUD}/${OPT}/caps-website/wing-one-on-one-peer-training`,

  /** wing-research-assessment.png */
  wingResearchAssessment: `${CLOUD}/${OPT}/caps-website/wing-research-assessment`,

};

export default images;
